FROM node:alpine3.22

# set a working directory inside container
WORKDIR /app

# copy only package.json file to working directory
# Done to speed up build process
COPY ./package.json .

# install node modules
RUN npm install

# copy all folders and file from host directory to working directory
# NOTE: If we are using volume mapping this step is redundant, but its required for prod deployment
COPY . .

# Default startup command when it starts as container
CMD ["npm", "run", "start"]