version: "4"

services:
  # dev server
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
    volumes:
      - /app/node_modules
      - .:/app

  # test server
  test:
    #  container will have an interactive terminal session, which is useful for running processes that expect to be attached to a terminal, such as development servers or debugging tools.
    # tty: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
