
services:
  redis-server:
    image: redis:alpine
    restart: unless-stopped

  visits-app:
    build: .
    ports:
      - "3000:8081"
    depends_on:
      - redis-server
    restart: unless-stopped
