name: react-app

on:
  push:
    branches:
      - main

jobs:
  build:
    # environment name from git hub
    environment: prod-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t prasanvb/4-react-app-test -f 4-react-app/Dockerfile.dev ./4-react-app

      - name: Run container and execute tests
        run: docker run -e CI=true prasanvb/4-react-app-test npm test

      - name: Create prod build package
        run: cd 4-react-app && npm install && npm run build

      - name: Generate deployment zip package
        run: cd 4-react-app && zip -r ../deploy.zip . -x '*.git*' 'node_modules/*'

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: 4-react-app
          environment_name: 4-react-app-prod-env
          existing_bucket_name: elasticbeanstalk-us-west-2-980921714626
          region: us-west-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
