name: react-app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub, create image and run tests
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build -t 4-react-app-test:latest -f Dockerfile.dev .
      - run: docker run -e CI=true 4-react-app-test:latest npm test
