name: react-app

on:
  push:
    branches:
      - main

jobs:
  build:
    # environment name from git hub
    environment: prod-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Add step run test later

      #NOTE: The Dockerfile will handle the build and install steps inside the container on AWS. The workflow just needs to package the app directory (with Dockerfile at the root) and deploy.

      - name: Generate deployment zip package
        run: cd 4-react-app && zip -r ../deploy.zip . -x '*.git*' 'node_modules/*'

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: 4-react-app
          environment_name: 4-react-app-prod-env
          existing_bucket_name: elasticbeanstalk-us-west-2-980921714626
          region: us-west-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
