name: react-app

on:
  push:
    branches:
      - main

jobs:
  build:
    environment: prod-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Print secret envs (safe debug)
        run: |
          echo "Username length: ${#DOCKERHUB_USERNAME}"
          echo "Token length: ${#DOCKERHUB_TOKEN}"
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t 4-react-app-test:latest -f Dockerfile.dev .

      - name: Run Tests
        run: docker run -e CI=true 4-react-app-test:latest npm test
