name: react-app

on:
  push:
    branches:
      - main

# NOTE:
# Workflow just needs create a zip package of the app directory (with Dockerfile at the root).
# Deploy to AWS Elastic Beanstalk web server environment using a managed Docker platform
# Elastic Beanstalk, detects Dockerfile, builds a Docker image and then runs that image as a container inside an EC2 instance.

jobs:
  build:
    # environment name from git hub
    environment: prod-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Run tests using dev Dockerfile
      - name: Build and Test (Dev)
        run: |
          docker build -t prasanvb/4-react-app-test -f 4-react-app/Dockerfile.dev ./4-react-app
          docker run -e CI=true prasanvb/4-react-app-test npm test

      # Package app for deployment (production Dockerfile must be present)
      - name: Create zip package for Deployment
        run: cd 4-react-app && zip -r ../deploy.zip . -x '*.git*' 'node_modules/*'

      # Deploy to AWS Elastic Beanstalk
      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: 4-react-app
          environment_name: 4-react-app-prod-env
          existing_bucket_name: elasticbeanstalk-us-west-2-980921714626
          region: us-west-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
